### ISSUE TITLE
Preserve comments

### ISSUE THREAD

**Issue by pornel** [Yamakaky/rust-bindgen#166]
Thanks to `rustdoc` comments in Rust are pretty valuable. It's be great if bindgen could copy comments from C headers.

I presume it's a hard problem. I wouldn't mind if comments weren't preserved very precisely. Having them at all is already a big improvement and would save me a lot of copy&pasting and conversion of `/*` to `//` (which is tedious).

**Comment by nox** [comment]
If you look in @michaelwu's fork, you will find some commits for comments (grep for "comment" and "doc").

https://github.com/crabtw/rust-bindgen/compare/master...michaelwu:sm-hacks

**Comment by Yamakaky** [comment]
Maybe with clang-rs, it would be easier. See http://kylemayes.com/clang-rs/all/clang/struct.Entity.html, `get_comment()`

**Comment by nox** [comment]
@Yamakaky This is kinda the same thing as @michaelwu but through an external crate. Switching to clang-rs might be a good thing in general though. Not sure we should do it now though, I think it's better to first triage through everything before starting big refactoring.

Btw are you on IRC?

**Comment by Yamakaky** [comment]
No. A link?

**Comment by nox** [comment]
I'm not at home right now, but I think it would be better to communicate rather than squatting users' tickets. ;)

I'm usually hanging around on #servo, #rust and #rust-fr on irc.mozilla.org.

**Comment by Yamakaky** [comment]
THIS CRATE IS DEPRECIATED, please use https://github.com/servo/rust-bindgen.
