### ISSUE TITLE
Wishlist: Detect `#pragma pack()` directives

### ISSUE THREAD

**Issue by emilio** [Yamakaky/rust-bindgen#235]
Before everything else: Thanks for maintaining this awesome project.

Today I used bindgen to make bindings to [tgl](https://github.com/vysheng/tgl).

I was getting a ton of segfaults without knowing why. Hours passed before I read https://github.com/vysheng/tgl/blob/master/tgl.h#L162 and realised what was going on:

```c
#pragma pack(push,4)
struct tgl_state {
// ...
```

It'd be great if bindgen could detect the alignment of the structure and do something like it does with unions (since for now rust has no syntax for explicit alignment), maybe at least emitting a warning when this directive is seen would be helpful.

I'd love to try to implement this when I have a bit more free time, so if you give me some advice I'll be happy to try.

**Comment by Yamakaky** [comment]
Closing for https://github.com/Yamakaky/rust-bindgen/issues/351
