### ISSUE TITLE
bitflags

### ISSUE THREAD

**Issue by Yamakaky** [Yamakaky/rust-bindgen#278]
We could detect bitflags enums like

``` rust
enum Flags {
    A = 0x1,
    B = 0x2,
    C = 0x4
}
```

and convert it using the `bitflags!`macro.
https://crates.io/crates/bitflags
Possible detection heuristic: if
- all variants have an associated constant
- all constants are a power of two
- the constants don't overlap

then we convert the enum using the macro.
Open questions:
- the generated file would have a dependency to this crate. Can we manually expand a macro?
- wich underlining type should we use ? u32 ?

**Comment by nox** [comment]
> the generated file would have a dependency to this crate. Can we manually expand a macro?

I don't think that's a problem. That crate is small and even comes with a `no_std` feature.

> wich underlining type should we use ? u32 ?

Our enum code is already able to determine which type to use, we can just reuse it.

**Comment by Yamakaky** [comment]
Maybe then I add a flag to use this macro.
