### ISSUE TITLE
Rc<Refcell<_>> -> Box<_>

### ISSUE THREAD

**Issue by Yamakaky** [Yamakaky/rust-bindgen#293]
In types.rs, there are a lot of Rc. I can't find in the code why it couldn't be replaced by Box. Did I miss something?

**Comment by Yamakaky** [comment]
The only possible issues I found is in parser.rs:405.

**Comment by Yamakaky** [comment]
For the record, it's this line https://github.com/crabtw/rust-bindgen/blob/master/src/parser.rs#L405.
I don't really understand this line, it checks if the objects are the same, and not simply if they are equals. Do you remember why you did that @crabtw?

**Comment by Yamakaky** [comment]
Other function which uses Rc explicitly: https://github.com/crabtw/rust-bindgen/blob/master/src/gen.rs#L36, used in https://github.com/crabtw/rust-bindgen/blob/master/src/gen.rs#L356.

**Comment by emilio** [comment]
The point of having `Rc<RefCell<T>>` is that the inner type can be modified from multiple holders at the same time, that doesn't happen with `Box<T>`. This allows you to update previous records instead of having to modify them one by one.

**Comment by Yamakaky** [comment]
That's my point: are we sure they are multiple owners or is it legacy code?

**Comment by emilio** [comment]
I'm pretty sure this can happen in anything that modifies it after calling `decl_name`. See [this](https://github.com/crabtw/rust-bindgen/blob/master/src/parser.rs#L479) for example.
