### ISSUE TITLE
Choose and document format of -match argument

### ISSUE THREAD

**Issue by Dr-Emann** [Yamakaky/rust-bindgen#300]
I wasn't able to find any documentation which specifies the format of the argument to the `-match` option (e.g. glob vs regex vs literal)

Looking at the implementation, it looks like the argument to `-match` is used as a literal string to check against the file path.

I think glob syntax might be the best fit, personally, but whatever the decision is, it should probably be documented in the output of `--help`

**Comment by Yamakaky** [comment]
> Only output bindings for definitions from files whose name contains <name>
Seems explicit to me.
