### ISSUE TITLE
Incorrect mapping of 64 bit system types

### ISSUE THREAD

**Issue by ousado** [Yamakaky/rust-bindgen#347]
I get output like e.g.

pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __off64_t = ::std::os::raw::c_long;

instead of c_[u]longlong

**Comment by ousado** [comment]
in case it matters, this is a debian Jessie x86_64 GNU/Linux system

**Comment by Yamakaky** [comment]
Can you give me the header you use?

**Comment by ousado** [comment]
@Yamakaky https://github.com/libevent/libevent/blob/master/include/event.h

**Comment by ousado** [comment]
btw, this project deserves the "second most useful project under the sun" award

**Comment by Yamakaky** [comment]
^^

**Comment by Yamakaky** [comment]
what's the first?

**Comment by Yamakaky** [comment]
try to run `__ino64_t my_ino; printf("%d\n", sizeof my_ino);`

**Comment by ousado** [comment]
haha :) well, I just don't like superlatives that much

**Comment by ousado** [comment]
@Yamakaky  that prints "8" 

it also generates wrong mappings for 
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
etc. -- all the 64 bit ones I can see here

**Comment by ousado** [comment]
if you get different output, which options do you use to run bindgen?

**Comment by Yamakaky** [comment]
https://doc.rust-lang.org/src/std/up/src/libstd/os/raw.rs.html#35-42
It should be ok, `long` is 64 bits on x86_64.

**Comment by Yamakaky** [comment]
`assert_eq!(8, std::mem::size_of::<std::os::raw::c_long>());`

**Comment by ousado** [comment]
@Yamakaky apparently I get the wrong type hint in vscode

**Comment by ousado** [comment]
@Yamakaky still, it would be better to generate these as c_[u]longlong - otherwise one /has/ to generate different bindings for 64 and 32 bit systems

**Comment by Yamakaky** [comment]
^^

**Comment by Yamakaky** [comment]
```c
#include <sys/types.h>

__ino64_t t;
```
`cpp t.c | grep 'typedef.*ino64_t'`
It's the right type.

**Comment by ousado** [comment]
int64_t is *always* 64 bit wide, no matter the architecture - c_long is just 64 bit wide on some architectures, I think the generated type should be consistent in that respect.

**Comment by Yamakaky** [comment]
After cpp on 64bit, __ino64_t is an unsigned long int, not a uint64_t.

**Comment by ousado** [comment]
it's not just about __ino64_t 

```rust
#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
pub type va_list = __gnuc_va_list;
pub type __gnuc_va_list = __builtin_va_list;
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_char;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
```

**Comment by Yamakaky** [comment]
I found no mention of __int8_t elsewhere. Its defined in `/usr/include/bits/types.h` as `signed char`, but doesn't seem used elsewhere in /usr/include. Do you know more about it?
bindgen already support natives intN_t and such.

**Comment by ousado** [comment]
cpp uses the arch-specific headers, of course
the problem I see with this is the following:
generating bindings on a 64 bit arch produces above types - which are correct on a 64 bit system.
but using those generated bindings to compile on a 32 bit arch uses wrong types - with probably not always easy-to-detect errors - I assume people use bindgen and then tweak the output, and ship it in source form, and don't run it again for every compilation on every system.

**Comment by Yamakaky** [comment]
I understand the problem, but what can we do?

**Comment by ousado** [comment]
I generated the headers again, with -DEVENT__HAVE_STDINT_H, which includes stdint.h,
the result looks slightly different:
it correctly generates
pub type int8_t = i8;
pub type int16_t = i16;
pub type int32_t = i32;
pub type int64_t = i64;
pub type uint8_t = u8;
pub type uint16_t = u16;
pub type uint32_t = u32;
pub type uint64_t = u64;
then there are the least and fast variants: 
pub type uint_least64_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
and the internal ones:
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
which still refer to the arch-specific types.

maybe a viable workaround would be to match against 8,16,32,64 in the type names for integer types, and map them to the respective widths. That's of course not entirely correct for user-defined types, but it would at least take care of the system types.

**Comment by Yamakaky** [comment]
Too bad C didn't have fixed-size types by default...
I'm not sure what to do. A whitelist is not very scalable...

**Comment by ousado** [comment]
@Yamakaky I guess a regex like "{|8|16|32|64|})_t$" would do, for the most part - and maybe a warning for other integer types containing 8|16|32|64. And then exposing an API and/or some configuration to map other integers to fixed sizes would be good, in the long run. 
I'm not sure whether it's even possible to figure this out 100% programatically.

**Comment by emilio** [comment]
@ousado that's a bad idea IMHO.

That would match even some standard types like `xxx_{least, max, fast}{8, 16, ...}_t`, that are not required at all to be the specified size.

**Comment by ousado** [comment]
@emilio all of those are required to be *at least* of the size indicated by the number (see link) - so it would at least map to types that are not too small, unlike currently, which is an actual issue.
It definitely would be an improvement over the current situation.

http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/stdint.h.html

**Comment by emilio** [comment]
@ousado: That'd be misleading and potentially cause bugs when calling the functions.

The ideal thing IMO would be to replace directly `uintxx_t` by the actual rust types when appropriate, instead of using the typedef. For example, a function like:

```c
void whatever(uint32_t arg);
```

would be translated to:

```rust
extern "C" fn whatever(arg: u32) -> ();
```

Thus keeping correctness when we *know* we're correct, and just relying on the architecture when we don't.

**Comment by ousado** [comment]
@emilio that already happens, and it doesn't capture many cases - that's what @Yamakaky refers to as maintaining a whitelist.

**Comment by emilio** [comment]
I don't see how another setup would be more reliable. Probably a way to
replace types could be convenient and easy enough to implement. But I
think this kind of replacements should be configured per-application,
not be bundled into bindgen.

**Comment by ousado** [comment]
It it also affects OS-specific types like rlim64_t, ino64_t,  fsfilcnt64_t etc. - that's a long list and using a 64_t postfix to indicate the size is a very common thing to do.

Well, yeah, ultimately making it configurable would be desirable, of course (see my "bad idea" comment ;) ). 
But given that making xxx64_t a 32 bit type is an error in like 99.9% of the cases, it's definitely more reliable to follow that convention.

**Comment by emilio** [comment]
On Mon, May 30, 2016 at 08:48:40AM -0700, ousado wrote:
> Well, yeah, ultimately making it configurable would be desirable, of
> course (see my "bad idea" comment ;) ).

Note that I was talking about the regex pattern idea, not the
configuration, but heh, touché :P

> But given that making xxx64_t a 32 bit type is an error in like 99.9%
> of the cases, it's definitely more reliable to follow that convention.

Yes, I still think it can be error-prone though, and that something like
it shouldn't be bundled into bindgen.

I'm not a maintainer though, so I guess @Yamakaky or other maintainer
would have to take the decision.

**Comment by ousado** [comment]
In any case, the user of bindgen must be aware of what's going on

**Comment by ousado** [comment]
The one problem I see is when code refer to bytes in numbers, instead of bits, using e.g. u1_t for unsigned char, and u8_t for uint64, etc. but that could be checked, so if the compiler says that a type is a c_ulong and has a 8_t postfix, the wider version should be preferred.

**Comment by Yamakaky** [comment]
If someone wants to PR ^^

**Comment by ousado** [comment]
@Yamakaky please take a good look, I'm completely new to rust.

**Comment by zackw** [comment]
I urge you NOT to do this.  It will fuck up any attempt to match C++ mangled names.

**Comment by Yamakaky** [comment]
THIS CRATE IS DEPRECIATED, please use https://github.com/servo/rust-bindgen.
