### ISSUE TITLE
const-ness not tracked for arrays as function arguments

### ISSUE THREAD

**Issue by bsteinb** [Yamakaky/rust-bindgen#350]
Commit 516f07e81bc83831a12eed0af4f2931419266e85 changed the way dynamically sized array types are handled, dropping the use of `TPtr` in favor of zero length `TArray`. `TArray`, however, does not track `const`-ness and `TArray`s which appear in function argument lists are [later unconditionally converted to mutable pointers](https://github.com/crabtw/rust-bindgen/blob/3bf74c44703b03aec69ea9041d1797cb19b69834/src/gen.rs#L1365). The following function prototype

``` c
void f(const int x[]);
```

used to be converted to this

``` rust
extern "C" {
    pub fn f(x: *const ::std::os::raw::c_int);
}
```

but now becomes this

``` rust
extern "C" {
    pub fn f(x: *mut ::std::os::raw::c_int);
}
```

**Comment by Yamakaky** [comment]
types.rs:TArray doesn't track const

**Comment by Yamakaky** [comment]
THIS CRATE IS DEPRECIATED, please use https://github.com/servo/rust-bindgen.
