### ISSUE TITLE
Please support repr(packed)

### ISSUE THREAD

**Issue by javagg** [Yamakaky/rust-bindgen#351]
Can we find a way to support this?

**Comment by Yamakaky** [comment]
```c
typedef struct __attribute__((__packed__))
{
    int a;
} Pote;
```
```
/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
#[repr(C, packed)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct Pote {
    pub a: ::std::os::raw::c_int,
}
impl ::std::default::Default for Pote {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
```

**Comment by javagg** [comment]
```
#pragma pack(push,1)
struct Info
{
	int version;
	int reserved[32];
};
#pragma pack(pop)
```
This is the way the packing is done when msvc is used. Maybe we need more work on this.

**Comment by burdges** [comment]
We almost started using rust-bindgen thinking this existed, but no dice.  Is this particularly hard for some reasons like the alignment not surviving clearly in LLVM's IR?

**Comment by Yamakaky** [comment]
`#pragma pack` is a msvc builtin, so I wouldn't be surprised if it wasn't supported at all by clang. Links, someone?

**Comment by burdges** [comment]
I suppose clang causes this issue?

```C
#include <stdint.h>
#define GNUNET_PACKED __attribute__((packed))
struct GNUNET_MessageHeader {
  uint16_t size GNUNET_PACKED;
  uint16_t type GNUNET_PACKED;
};
```

```Rust
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Struct_GNUNET_MessageHeader {
    pub size: uint16_t,
    pub _type: uint16_t,
}
```
```

**Comment by Yamakaky** [comment]
For `pragma pack`, try enabling the [Microsoft extensions](http://llvm.org/releases/3.4/tools/clang/docs/UsersManual.html#microsoft-extensions). If it works, I will add a mention on the readme.

**Comment by burdges** [comment]
It does not on my end.  It's only placing `__attribute__((packed))` after/on the struct helps. Appears GCC [allows both forms](https://gcc.gnu.org/onlinedocs/gcc-3.3/gcc/Type-Attributes.html) but described placing it after/on the struct first, and then says you can place it on the members.  I'd suppose clang never implemented that second option.

**Comment by emilio** [comment]
Clang does support `#pragma` packing, and while it does not expose that attribute in the ast (it marks it as `CXCursor_UnexposedAttr`), we probably can detect packing with `clang_Cursor_getOffsetOfField` or `clang_Type_getOffsetOf`.

**Comment by Yamakaky** [comment]
If someone wants to PR...

**Comment by retep998** [comment]
Also note that `#pragma pack` can specify values other than `1`, so this also somewhat depends on https://github.com/rust-lang/rust/issues/33158 being implemented.

**Comment by Yamakaky** [comment]
THIS CRATE IS DEPRECIATED, please use https://github.com/servo/rust-bindgen.
