### ISSUE TITLE
Command-line flag to remove the prefix for Option

### ISSUE THREAD

**Issue by jethrogb** [Yamakaky/rust-bindgen#352]
bindgen will currently output `Option`s like `::std::option::Option` (for example to represent nullable function pointers) or `::core::...` with `--use-core`.

It would be nice if there was a way to output just `Option`.

I don't know if there are any other uses of `::std` that might need similar treatment.

**Comment by Yamakaky** [comment]
`--use-core`

**Comment by jethrogb** [comment]
Sorry, I had just built an older version of bindgen for #212 and didn't see the flag in the help... Updated above.

**Comment by Yamakaky** [comment]
So, it's not an issue?

**Comment by jethrogb** [comment]
More like an enhancement request? See above.

**Comment by Yamakaky** [comment]
See https://github.com/crabtw/rust-bindgen/issues/316#issuecomment-221024480 for the problem. Maybe then prefix: `Option` -> `Option_`, like with the reserved keywords?
Btw, it should consistent with `Default`, `zeroed()`, ...

**Comment by jethrogb** [comment]
Ah, I see. If it's too complicated I guess a find/replace will work fine.

**Comment by Yamakaky** [comment]
Not really, it's just a string to add in the list of builtins to replace. What's your usecase exactly? `--use-core` isn't sufficient?

**Comment by jethrogb** [comment]
It's sufficient but it's just very verbose.

**Comment by Yamakaky** [comment]
The prefix is not present in the output of `cargo doc`.

**Comment by Yamakaky** [comment]
THIS CRATE IS DEPRECIATED, please use https://github.com/servo/rust-bindgen.
