### ISSUE TITLE
http://llvm.org/apt/ down

### ISSUE THREAD

**Issue by Yamakaky** [Yamakaky/rust-bindgen#357]
The travis build fails because of that.

**Comment by blanham** [comment]
There's discussion on the LLVM mailing list here: http://thread.gmane.org/gmane.comp.compilers.llvm.devel/99556 They are not sure when it will be back, or even if it will be back at all.

**Comment by KyleMayes** [comment]
I fixed `clang-sys`'s Travis build by downloading and extracting the binaries from llvm.org ([.travis.yml](https://github.com/KyleMayes/clang-sys/blob/d7bf5993cf7da564400368266c36bef59b446fde/.travis.yml)).
