### ISSUE TITLE
Cannot install bindgen on Windows

### ISSUE THREAD

**Issue by JPGygax68** [Yamakaky/rust-bindgen#384]
I'm tried Rust 0.10 stable, beta 0.11 and the last two 0.12 nightlies (2016-08-17, 2016-08-18). Trying to run `cargo install bindgen` consistently fails with an error message 

```
thread 'main' panicked at 'could not find libclang.lib, set the LIBCLANG_PATH environment variable to a path where libclang.lib can be found', C:\Users\gygax\.cargo\registry\src\github.com-1ecc6299db9ec823\clang-sys-0.7.2\build.rs:42
```

The above is when `LIBCLANG_PATH` is set to `D:\Program Files\LLVM\bin` where CLang is currently installed. If I set it to `D:\Program Files\LLVM\lib`, the message changes to say that `libclang.dll` cannot be found. I tried setting the value to include both paths (lib and bin) separated by a semicolon, without success (still `could not find libclang.dll`.

**Comment by retep998** [comment]
What you should do is add `D:\Program Files\LLVM\bin` to your `PATH` and `D:\Program Files\LLVM\lib` to your `LIBCLANG_PATH`.

**Comment by JPGygax68** [comment]
I have done so now (but I think I had already tried that). No change, 
cargo still tells me to set LIBCLANG_PATH so that it can find libclang.dll.

**Comment by retep998** [comment]
Works fine for me.
```
C:\msys64\home\Peter> $env:LIBCLANG_PATH = "C:\Program Files\LLVM\lib"
C:\msys64\home\Peter> cargo install bindgen
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading bindgen v0.19.0
 Downloading clang-sys v0.7.2
 Downloading syntex_syntax v0.38.0
 Downloading cexpr v0.1.3
 Downloading syntex_errors v0.38.0
 Downloading syntex_pos v0.38.0
   Compiling rustc-serialize v0.3.19
   Compiling strsim v0.3.0
   Compiling bitflags v0.7.0
   Compiling bitflags v0.5.0
   Compiling winapi v0.2.8
   Compiling libc v0.2.15
   Compiling unicode-xid v0.0.3
   Compiling nom v1.2.4
   Compiling glob v0.2.11
   Compiling utf8-ranges v0.1.3
   Compiling clang-sys v0.7.2
   Compiling log v0.3.6
   Compiling memchr v0.1.11
   Compiling regex-syntax v0.3.4
   Compiling cexpr v0.1.3
   Compiling syntex_pos v0.38.0
   Compiling aho-corasick v0.5.2
   Compiling winapi-build v0.1.1
   Compiling lazy_static v0.2.1
   Compiling kernel32-sys v0.2.2
   Compiling term v0.4.4
   Compiling thread-id v2.0.0
   Compiling thread_local v0.2.6
   Compiling regex v0.1.73
   Compiling syntex_errors v0.38.0
   Compiling syntex_syntax v0.38.0
   Compiling docopt v0.6.82
   Compiling env_logger v0.3.4
   Compiling bindgen v0.19.0
    Finished release [optimized] target(s) in 435.40 secs
  Installing C:\Users\Peter\AppData\Local\Rust\bin\bindgen.exe
C:\msys64\home\Peter> rustc -vV
rustc 1.12.0-nightly (080e0e072 2016-08-08)
binary: rustc
commit-hash: 080e0e072f9c654893839cf1f7ea71dc153b08a9
commit-date: 2016-08-08
host: x86_64-pc-windows-msvc
release: 1.12.0-nightly
```

**Comment by JPGygax68** [comment]
Thank you Peter,

I see you're using MSys - I'm working with Visual Studio 2015. Should I 
switch ? I have no compelling reason to use one over the other in this case.

**Comment by retep998** [comment]
@JPGygax68 No, I'm not using msys. I just happen to have my home directory inside msys2 because I'm too lazy to move it somewhere else. I am using the msvc version of Rust, with Visual Studio 2015 installed.

Which version of Rust are you using? Are you using the msvc version of Rust?

In your `D:\Program Files\LLVM\bin` do you have a `libclang.dll` and in `D:\Program Files\LLVM\lib` do you have a `libclang.lib`, with precisely those exact names?

**Comment by JPGygax68** [comment]
The Rust install package `rust-nightly-x86_64-pc-windows-msvc.msi`, dated 2016-08-18.

Yes, both the import library and the dll are in their proper place.

**Comment by retep998** [comment]
Are you sure you didn't accidentally capitalize the `lib` or `bin` in your `LIBCLANG_PATH`? According to the build script for `clang-sys`, if it can't find the file in the given directory, but the directory ends in exactly `lib` or `bin` (case sensitive!), then it looks in the other directory.

https://github.com/KyleMayes/clang-sys/blob/master/build.rs#L90-L104

**Comment by JPGygax68** [comment]
Here's my environment:
```
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\gygax\AppData\Roaming
BONJOUR_SDK_HOME=D:\Program Files\Bonjour SDK\
CLANG_PATH=D:\Program Files (x86)\LLVM\bin
COMMANDER_DRIVE=C:
COMMANDER_EXE=C:\totalcmd\TOTALCMD64.EXE
COMMANDER_INI=C:\Users\gygax\AppData\Roaming\GHISLER\WINCMD.INI
COMMANDER_PATH=C:\totalcmd
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-OMQBER9
ComSpec=C:\WINDOWS\system32\cmd.exe
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
CUDA_PATH_V7_5=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
C_EM64T_REDIST11=C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\
GTK_BASEPATH=C:\Program Files (x86)\GtkSharp\2.12\
HOMEDRIVE=C:
HOMEPATH=\Users\gygax
INTELMEDIASDKROOT=C:\Program Files (x86)\IntelSWTools\Intel(R)_Media_SDK_2016.0.1\
INTELMEDIASDK_WINSDK_PATH=C:\Program Files (x86)\Windows Kits\8.1
LIBCLANG_LIB=D:\Program Files\LLVM\lib
LIBCLANG_PATH=D:\Program Files\LLVM\lib
LIBCLANG_STATIC_PATH=D:\Program Files\LLVM\lib
LOCALAPPDATA=C:\Users\gygax\AppData\Local
LOGONSERVER=\\MicrosoftAccount
NUMBER_OF_PROCESSORS=4
NVCUDASAMPLES7_5_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v7.5
NVCUDASAMPLES_ROOT=C:\ProgramData\NVIDIA Corporation\CUDA Samples\v7.5
NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
OS=Windows_NT
Path=C:\Program Files\Rust nightly MSVC 1.12\bin;D:\Program Files\LLVM\bin;D:\Program Files\CMake\bin;d:\Program Files (x86)\Conan\conan;d:\VulkanSDK\1.0.8.0\Bin;C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\bin\Intel64;d:\Libraries\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\libnvvp;C:\Program Files (x86)\IntelSWTools\Intel(R)_Media_SDK_2016.0.1\bin\x64;C:\Program Files (x86)\IntelSWTools\Intel(R)_Media_SDK_2016.0.1\bin\win32;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\gygax\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;D:\Program Files\nw\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;D:\Program Files\nodejs\;D:\Program Files\NASM;D:\Program Files (x86)\CMake\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\gygax\AppData\Roaming\npm;C:\Users\gygax\AppData\Local\atom\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3c03
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\gygax\AppData\Local\Temp
TMP=C:\Users\gygax\AppData\Local\Temp
USERDOMAIN=DESKTOP-OMQBER9
USERDOMAIN_ROAMINGPROFILE=DESKTOP-OMQBER9
USERNAME=gygax
USERPROFILE=C:\Users\gygax
VK_SDK_PATH=d:\VulkanSDK\1.0.8.0
VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
VULKAN_SDK=d:\VulkanSDK\1.0.8.0
windir=C:\WINDOWS
```

**Comment by mschorsch** [comment]
It seems there are some failures in your environment settings.

1. Your `CLANG_PATH` variable points to a LLVM 32-bit installation, while all other `LIBCLANG_*` env vars refer to a 64-bit installation.
2. `LIBCLANG_LIB` is not a valid env var for LLVM.

Installation with msvc 64-bit (according to your env vars)
1. Change your toolchain `rustup default stable-x86_64-pc-windows-msvc`.
2. Set `$env:CLANG_PATH='D:\Program Files\LLVM\bin'`
3. Set `$env:LIBCLANG_PATH='D:\Program Files\LLVM\lib'`
4. Set `$env:LIBCLANG_STATIC_PATH='D:\Program Files\LLVM\lib'`
5. Copy `D:\Program Files\LLVM\bin\libclang.dll` to `D:\Program Files\LLVM\lib\libclang.dll` (`Copy-Item D:\Program Files\LLVM\bin\libclang.dll D:\Program Files\LLVM\lib\libclang.dll`)
6. `cargo install bindgen`

**Comment by JPGygax68** [comment]
Thanks a lot @mshorsch, item 5 - copying the DLL - did the trick!

It seems strange though, having to copy a DLL manually - is this really as intended ?

**Comment by mschorsch** [comment]
I think no, but I haven't found any other solution.

**Comment by retep998** [comment]
It works fine for me without copying the DLL.

**Comment by mschorsch** [comment]
Hi retep998,

i have looked at the problem again. It seems that the crate `clang-sys` scans for certain windows paths (see [https://github.com/KyleMayes/clang-sys/blob/ca445a0f3181b2077c4e563f46c9d0e645332a51/build.rs#L76-L82](https://github.com/KyleMayes/clang-sys/blob/ca445a0f3181b2077c4e563f46c9d0e645332a51/build.rs#L76-L82)). You have installed LLVM in the directory `C:\Program Files\LLVM\lib`, for this reason, all libraries are found. I think `clang-sys` should also include the environment variable `CLANG_PATH` in the search path.

**Comment by RReverser** [comment]
Sounds like similar issue on OSX:

> dyld: Library not loaded: @rpath/libclang.dylib
  Referenced from: /Users/generic/.cargo/bin/bindgen
  Reason: image not found
fish: 'bindgen --help' terminated by signal SIGABRT (Abort)

**Comment by trevoranderson** [comment]
@RReverser 
Fixed the OSX issue by simlinking libclang.dylib in /usr/local/lib. The natively installed one was at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib

**Comment by Yamakaky** [comment]
THIS CRATE IS DEPRECIATED, please use https://github.com/servo/rust-bindgen.
