### ISSUE TITLE
Functional macros are not supported

### ISSUE THREAD

**Issue by Slabity** [Yamakaky/rust-bindgen#388]
Take the following code for example:

``` C
#define multiply(a,b) a*b
#define A 5
#define B 10
#define AB multiply(A,B)
#define BA A*B
```

Bindgen will spit out:

```
/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
pub const A: ::std::os::raw::c_uchar = 5;
pub const B: ::std::os::raw::c_uchar = 10;
pub const BA: ::std::os::raw::c_uchar = 50;
```

The macro `AB` is missing. In cases of macros that have many macro functions as a part of them (for example, the `_IO*` macros for ioctls on UNIX platforms), it would be really useful to have bindgen try and evaluate the macro and give the resulting value if possible.

**Comment by jethrogb** [comment]
The underlying issue is that functional macros are not supported.

**Comment by Slabity** [comment]
Servo's bindgen supports functional macros as long as they evaluate to a type that can be converted.

Could that feature be brought over?

**Comment by jethrogb** [comment]
I'm not sure what you're talking about. Servo's bindgen doesn't even support expression parsing in macros.

**Comment by Slabity** [comment]
Nevermind. It appears Servo's bindgen attempts to parse the macros I've been testing it with, but it does not produce the correct value.

However, I still would like functional macros to be supported. It is especially useful in retrieving ioctl numbers that are defined with macros like `_IO`.

**Comment by Yamakaky** [comment]
THIS CRATE IS DEPRECIATED, please use https://github.com/servo/rust-bindgen.
