### ISSUE TITLE
Forbidden #[derive(Debug)] is generated on a struct which hosts non-debuggable items.

### ISSUE THREAD

**Issue by snuk182** [Yamakaky/rust-bindgen#389]
I have applied bindgen to the following file:
https://github.com/vurtun/nuklear/blob/929d74a3381a0e383e02d3c5079a100bdd3b0687/nuklear.h
Got the result, which is not compiled, here is why:

``` #[repr(C)]
#[derive(Copy)]
pub struct nk_page_data {
    pub _bindgen_data_: [u64; 45usize],
}

// ...

#[repr(C)]
#[derive(Copy)]
pub struct nk_page_element {
    pub data: nk_page_data,
    pub next: *mut nk_page_element,
    pub prev: *mut nk_page_element,
}

// ... 

#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct nk_page {
    pub size: ::std::os::raw::c_uint,
    pub next: *mut nk_page,
    pub win: [nk_page_element; 1usize],
}
```

Here **nk_page** derives Debug, which is forbidden cause **nk_page_element** contains **nk_page_data**, for which Debug deriving is forbidden because of inner array length > 32, for which [Debug deriving is not supported](https://doc.rust-lang.org/std/fmt/trait.Debug.html).

**Comment by Yamakaky** [comment]
hum, should be detected

**Comment by Yamakaky** [comment]
THIS CRATE IS DEPRECIATED, please use https://github.com/servo/rust-bindgen.
