### ISSUE TITLE
dyld: Library not loaded: @rpath/libclang.dylib

### ISSUE THREAD

**Issue by philippkeller** [Yamakaky/rust-bindgen#392]
Building bindgen on my OS X (Yosemite) all works fine but once I execute it:

```
> target/debug/bindgen
dyld: Library not loaded: @rpath/libclang.dylib
  Referenced from: /Users/philipp/local.ch/rust-bindgen/target/debug/bindgen
  Reason: image not found
Trace/BPT trap: 5
```

my `libclang.dylib` is here: `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib`

and `xcode-select -p` outputs `/Applications/Xcode.app/Contents/Developer`, so all seems fine. Any hints?

**Comment by Yamakaky** [comment]
You should report it to https://github.com/KyleMayes/clang-sys/
