### ISSUE TITLE
Update bindgen_plugin to 0.19.0

### ISSUE THREAD

**Issue by KenanSulayman** [Yamakaky/rust-bindgen#394]
Hey,

please update the bindgen_plugin to the latest version :-)

**Comment by Yamakaky** [comment]
Well, I started https://github.com/Yamakaky/rust-bindgen/pull/334 some time ago, it had a blocking bug from rustc I think, I don't remember which.

**Comment by Yamakaky** [comment]
THIS CRATE IS DEPRECIATED, please use https://github.com/servo/rust-bindgen.
