### ISSUE TITLE
OOM Error on ixjuser.h

### ISSUE THREAD

**Issue by valarauca** [Yamakaky/rust-bindgen#395]
On the kernel header file [ixjuser.h](http://lxr.free-electrons.com/source/include/uapi/linux/ixjuser.h) bindgen triggers an OOM error. 

[Here is my code](https://github.com/valarauca/lib_uapi_linux/blob/master/build.rs) that is calling bindgen. I'm trying to generate bindings for the linux_uapi headers. It is a work in progress nowhere near done.

Platform specific info: 
- Ubuntu 14.04
-  x86_64 kernel 4.4.0-38-generic
- clang v3.8.0
- rustc v1.12.0

**Comment by Yamakaky** [comment]
THIS CRATE IS DEPRECIATED, please use https://github.com/servo/rust-bindgen.
