### ISSUE TITLE
Support CXType_Elaborated

### ISSUE THREAD

**Issue by tkonolige** [Yamakaky/rust-bindgen#399]
I'm getting the following error when trying to bind to MKL on OS X.

```
ERROR:bindgen: unsupported type `CXTypeKind(119)` (/opt/intel/mkl/include/mkl_types.h:40:3)
```

It looks like the issue is that `CXType_Elaborated` isn't supported by rust-bindgen yet.

**Comment by jpernst** [comment]
I've just run into this as well. This makes any struct typedef unbindable since refering to a struct by its tag name is an "elaborated type". My fork has a quick fix to get this working, but it's not quite PR ready since the fix requires clang 3.9.

**Comment by emilio** [comment]
Yeah, `Elaborated` is 3.9 only. We handle this with a feature in servo/rust-bindgen (support was added in https://github.com/servo/rust-bindgen/pull/6, but it's been completely rewritten since).

**Comment by Yamakaky** [comment]
THIS CRATE IS DEPRECIATED, please use https://github.com/servo/rust-bindgen.
