### ISSUE TITLE
typedef with struct or union broken with clang 3.9

### ISSUE THREAD

**Issue by cpavlina** [Yamakaky/rust-bindgen#400]
With latest bindgen installed from master, typedefs with structs and unions (possibly not an exhaustive list) are broken. Simple test:

```
% echo 'typedef struct { int x; } test;' > test.h
% bindgen test.h
ERROR:bindgen: unsupported type `Invalid` (test.h:1:27)
```

clang version:

```
clang version 3.9.0 (tags/RELEASE_390/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

clang 3.8.1 worked.

**Comment by Yamakaky** [comment]
hum...

**Comment by ctaggart** [comment]
I had the same problem with clang 3.9.0 on Windows. I downgraded to 3.8.1 and bindgen worked fine.

**Comment by Yamakaky** [comment]
Did you try https://github.com/servo/rust-bindgen?

**Comment by ctaggart** [comment]
@Yamakaky I haven't yet, but next time I need to do a bindgen, I may give it a shot.

**Comment by cpavlina** [comment]
https://github.com/servo/rust-bindgen does work for me with this basic test. Unfortunately it lacks a couple features I require, so I'm going to continue using this one.

**Comment by emilio** [comment]
Just for reference, which features does it lack?

Feel free to fill issues asking for them, we try to be responsive :)

**Comment by cpavlina** [comment]
`--use-core`, in particular. `--ctypes-prefix` as well, but I can work around that. Was also going to say `--convert-macros` but you seem to have just made that the default.

I can probably work around all of these by filtering the output, but currently the solution of "downgrade clang to 3.8" is working for me until one or both bindgens catch up...

**Comment by grossws** [comment]
`typedef enum smbc_share_mode {...} smbc_share_mode;` is also broken:
```
-> % bindgen --link smbclient --match libsmbclient.h /usr/include/samba-4.0/libsmbclient.h                                  
ERROR:bindgen: unsupported type `CXTypeKind(119)` (/usr/include/samba-4.0/libsmbclient.h:164:3)
```

Fails with clang/llvm `3.9.0` and works with `3.8.1`

**Comment by Yamakaky** [comment]
THIS CRATE IS DEPRECIATED, please use https://github.com/servo/rust-bindgen.
