### ISSUE TITLE
generate() fails with no message?

### ISSUE THREAD

**Issue by lewmpk** [Yamakaky/rust-bindgen#405]
Seems like there's no meaningful error. Or maybe i'm doing something wrong 

`RUST_BACKTRACE=1 cargo build                                                                                                               
error: failed to run custom build command for `**** v0.1.0 (file:///Users/lewmpk/Workspace/rusttv)`
process didn't exit successfully: `.../target/debug/build/***-4f6e9e0d62c62054/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Failed to generate bindings: ()', ../src/libcore/result.rs:799
stack backtrace:
   1:        0x10fb168f8 - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:        0x10fb1a7af - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:        0x10fb19825 - std::panicking::default_hook::h0ac3811ec7cee78c
   4:        0x10fb19dd6 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:        0x10fb19c74 - std::panicking::begin_panic::h6ed03353807cf54d
   6:        0x10fb19b92 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
   7:        0x10fb19af7 - rust_begin_unwind
   8:        0x10fb41730 - core::panicking::panic_fmt::h27224b181f9f037f
   9:        0x10f473dfe - core::result::unwrap_failed::h79dd658ded8cbd6d
  10:        0x10f471ba8 - <core::result::Result<T, E>>::expect::habb747d9733ba00f
  11:        0x10f47ce52 - build_script_build::main::hfa8bec8ab0b15ea0
  12:        0x10fb1ad6a - __rust_maybe_catch_panic
  13:        0x10fb19366 - std::rt::lang_start::h538f8960e7644c80
  14:        0x10f47d1f9 - main`

I'm also able to generate bindings via commandline.

**Comment by Yamakaky** [comment]
THIS CRATE IS DEPRECIATED, please use https://github.com/servo/rust-bindgen.
