### ISSUE TITLE
function arguments that are arrays behind typedefs are not translated correctly

### ISSUE THREAD

**Issue by lspitzner** [Yamakaky/rust-bindgen#407]
~~~~.c
// foo.h
typedef float myVector3[3];
void modifyVectorFunc(myVector3 v);
~~~~

currently produces

~~~~.rust
// foo.rs
pub type myVector3 = [f32; 3usize];
extern "C" {
    pub fn modifyVectorFunc(v: myVector3);
}
~~~~

but should be

~~~~.rust
pub type myVector3 = [f32; 3usize];
extern "C" {
    pub fn modifyVectorFunc(v: *mut float);
}
~~~~

or something like that; maybe `*mut dVector3` would work too.

#350 is roughly related.

**Comment by emilio** [comment]
Apparently we can close issues cross-repo? That sounds like a github bug (since nor me nor bors I think have access to this repo).

Feel free to re-open this issue, since it's not fixed in this version of bindgen. It's fixed in Servo's one though.

**Comment by emilio** [comment]
Well, it seems that bors had access to this repo, which explains it. But same, feel free to re-open (I can't manually since I have no access).

**Comment by lspitzner** [comment]
that was quick, thanks! i don't see through the project/fork structure, and thus don't really see if this needs reopening. I think i can make this work already.
(Also I don't have the option to reopen either. oh, the owner at least can, apparently :)

**Comment by Yamakaky** [comment]
THIS CRATE IS DEPRECIATED, please use https://github.com/servo/rust-bindgen.
