### ISSUE TITLE
Custom use declarations

### ISSUE THREAD

**Issue by Noxivs** [Yamakaky/rust-bindgen#408]
Hi,

I would like to know what  is the best way to add custom  ```use``` declarations. 

Currently i add manually my declarations when i have to. Perhaps there is a way to add to the ```pprust``` instance the declarations ?

**Comment by Yamakaky** [comment]
For now, you can't...

**Comment by emilio** [comment]
FWIW in the [servo version](https://github.com/servo/rust-bindgen) you can use the `--raw-line` flag or the `raw_line` builder method to do so.

**Comment by Yamakaky** [comment]
THIS CRATE IS DEPRECIATED, please use https://github.com/servo/rust-bindgen.
