### ISSUE TITLE
`decltype` failure.

### ISSUE THREAD

**Issue by kkimdev** [Yamakaky/rust-bindgen#410]
It looks like `decltype` type alias is not supported yet? I'm getting lines like these

```Rust
pub type std_unique_ptr__Pointer_type = decltype(__test<_Del>(0));
```
```
error: expected one of `!`, `+`, `,`, or `::`, found `(`
    --> src/generated.rs:1073:62
     |
1073 | pub type std_unique_ptr__Pointer_type = decltype(__test<_Del>(0));
```

**Comment by emilio** [comment]
I guess this issue goes into servo/rust-bindgen instead of here?

If that's the case, then it's a known bug with an open PR I need to address comments for: https://github.com/servo/rust-bindgen/issues/381

**Comment by emilio** [comment]
Oh, and current workaround is blacklisting/making that type opaque.

**Comment by kkimdev** [comment]
Oh, I mistakenly filed here. Thanks! :)
