### ISSUE TITLE
Bool arguments and return values are translated as c_int

### ISSUE THREAD

**Issue by mahkoh** [Yamakaky/rust-bindgen#98]
bindgen turns _Bool into c_int which is wrong in general. sizeof(bool) = 1 on x86_64 linux.

**Comment by nox** [comment]
This is now properly translated to `u8`, but this needs tests. Making them into proper `bool` will be done later.

**Comment by Yamakaky** [comment]
THIS CRATE IS DEPRECIATED, please use https://github.com/servo/rust-bindgen.
